name: care_task
description: "A new Flutter project."

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1  # Efficient image caching
  flutter_bloc: ^9.0.0          # State management using BLoC cubit pattern
  flutter_screenutil: ^5.9.3    # Responsive UI scaling
  freezed: ^2.5.7               # Immutable data classes
  freezed_annotation: ^2.4.4    # Code generation for Freezed
  get_it: ^8.0.3                # Dependency injection
  hive_flutter: ^1.1.0          # Local storage using Hive
  http: ^1.3.0                  # HTTP requests to fetch data
  json_serializable: ^6.9.0     # JSON serialization

dev_dependencies:
  hive_generator: ^2.0.1        # Code generation for Hive
  build_runner: ^2.4.13         # Code generator utility
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
